[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "ghostscript"]

[phases.install]
cmds = [
  "python3 -m virtualenv /app/venv",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT"
